export const people = [
  { name: "Bob", favouritemeal: "toad in the hole" },
  { name: "Dave", favouritemeal: "full english" },
  { name: "Barrack", favouritemeal: "cheeseburger" },
  { name: "Johnny", favouritemeal: "unsalted chicken, unpaid" },
  { name: "Karen", favouritemeal: "unsalted chicken, unpaid" },
  { name: "Chad", favouritemeal: "protein suppliments" },
  { name: "Robbie", favouritemeal: "edibles" },
  { name: "Cher", favouritemeal: "fake garlic" },
  { name: "Posh spice", favouritemeal: "salad" },
  { name: "Rihanna", favouritemeal: "eggs for breakfast" },
  { name: "David", favouritemeal: "jacket potato" },
  { name: "Jordan", favouritemeal: "mars bars" },
  { name: "Liz", favouritemeal: "broccoli and brie pie" },
  { name: "Arshi", favouritemeal: "steak?" },
  { name: "Loz", favouritemeal: "jam sandwich" },
  { name: "Charlotte", favouritemeal: "pizza" },
  { name: "Helen", favouritemeal: "css files" },
  { name: "Chris", favouritemeal: "KFC" },
  { name: "Mum", favouritemeal: "sunday roast" },
  { name: "Mr. sainsbury", favouritemeal: "pound coins" },
];
